# Generated by Django 3.0.5 on 2020-06-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tressapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz',
            new_name='name',
        ),
    ]
